In [2]:
import numpy as np

In [4]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [40]:
x=np.array(['a',40,12,51,65,95,98])
x

array(['a', '40', '12', '51', '65', '95', '98'], dtype='<U11')

In [58]:
print(type(x))
print(x.shape)

<class 'numpy.ndarray'>
(7,)


In [44]:
print(x.dtype)

<U11


In [52]:
a2=np.array([[10,30],[40,30]])

In [56]:
print(a2)
print(type(a2))
print(a2.shape)

[[10 30]
 [40 30]]
<class 'numpy.ndarray'>
(2, 2)


In [60]:
a=np.array([10,20,30,40])
b=a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [76]:
c=np.arange(-9,11)
print(c)

[-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5  6  7  8  9 10]


In [78]:
d=np.array([1.34665,3.4896,5.2679])
np.around(d,3)

array([1.347, 3.49 , 5.268])

In [82]:
print(np.around(np.sqrt(d),2))

[1.16 1.87 2.3 ]


In [90]:
a1=np.array([[3.0,4,5,6],[7,8,9,np.NaN]])
print(a1)

[[ 3.  4.  5.  6.]
 [ 7.  8.  9. nan]]


In [92]:
a1_copy=a1.astype(float)
print(a1_copy)

[[ 3.  4.  5.  6.]
 [ 7.  8.  9. nan]]


In [94]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
print(a2.sum(axis=1))

[40 70]


In [104]:
print(np.mean(mat,axis=1))

[2. 5. 8.]


In [113]:
np.fill_diagonal(mat,0)
print(mat)

[[0 2 3]
 [4 0 6]
 [7 8 0]]


In [119]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

In [121]:
print(a.T)

[[1 3]
 [2 4]]


In [125]:
a4=np.array([[1,2],[3,4],[5,6],[7,8]])
a4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [127]:
a4[2][1]

6

In [131]:
a5=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [155]:
a4[1:3,0:2]

array([[3, 4],
       [5, 6]])